services:
  docs:
    image: django_test_app_local_docs
    container_name: django_test_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_test_app:/app/django_test_app:z
    ports:
      - '9000:9000'
    command: /start-docs
